### ISSUE TITLE
can get user infor. plz help

### ISSUE THREAD

**Issue by thanhnguyen1121** [imsurajsharma/TikTokAPI-Unofficial#1]
tiktok updated the countries that are not allowed to access. So I could not get user information. Can you help me?

**Comment by imsurajsharma** [comment]
I can't help you as tiktok is ban in India

**Comment by thanhnguyen1121** [comment]
I'm in Vietnam and I can't access tiktok either!

**Comment by imsurajsharma** [comment]
Also, I don't have time for this. Sorry

**Comment by thanhnguyen1121** [comment]
I will try to find a solution. If possible I will update the code here. ^_^

**Comment by imsurajsharma** [comment]
Sure...i will. Thanks
